#!/bin/bash

struptime=`uptime | awk '{print $2,$3,$4,$5}'`
struptime1=${struptime%,}
strdayshours=${struptime1%%:*}' Hours, '
strminutes=${struptime1##*:}' Minutes'

echo "System Uptime -" $strdayshours$strminutes

exit 0
